version: '3'

services:
  app:
    ports:
      - ${PUBLISHED_APP}:8080
    depends_on:
      - mysql
      - redis

    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      # Database Configuration
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

      # JPA Configuration
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect

      # Redis Configuration
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: "backend"

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.29
    volumes:
      - ${DB_DATA_PATH}:/data/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
#      - TIMEZONE=${TIMEZONE}
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: "mysql"

  redis:
    image: redis:8.0
    volumes:
      - ${REDIS_DATA_PATH}:/data/redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    container_name: "redis"
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}

volumes:
  shared-data:

